[project]
name = "pyspark-kubernetes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyspark==4.0.0",
]

[tool.setuptools]
py-modules = []