apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark
  namespace: spark
rules:
- resources:
  - pods
  - services
  - persistentvolumeclaims
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete
  - deletecollection
- resources:
  - configmaps
  apiGroups:
  - ""
  verbs:
  - create
  - get
  - list
  - patch
  - delete
  - deletecollection
